package com.experian.test.api.config.properties;

public enum ServiceName {
    CHILDMONITORING                 ("childmonitoring"),
    IDAAS_CUSTOMERS                 ("idaascustomers"),
    CUSTOMERS                       ("customers"),
    CUSTOMERS_NEW                   ("customers_new"),
    ADDRESSES                       ("addresses"),
    COMMUNICATION_PROFILE           ("communicationprofile"),
    SUPPLEMENTAL_ADDRESSES          ("supplementaladdresses"),
    SUPPLEMENTAL_ADDRESSES_AUDIT    ("supplementaladdressesaudit"),
    LOGIN_HISTORY                   ("loginhistory"),
    PROSPECTS                       ("prospects"),
    COMMUNICATION_PROFILE_HISTORY   ("communicationprofilehistory"),
    CUSTOMER_HISTORY                ("customerhistory"),
    CONVERSION                      ("conversion"),
    WASP                            ("wasp"),
    BUREAUCHANGENOTIFICATION        ("bureauchangenotification"),
    BUREAU                          ("bureau"),
    BATCH_REPORTPULL                ("batchreportpull"),
    BUREAU_AUTH                     ("bureauauth"),
    BENEFITS                        ("benefits"),
    SCORES                          ("scores"),
    ORCHESTRATION                   ("orchestrationlogin"),
    SSO                             ("sso"),
    SECURE_TOKEN                    ("securetoken"),
    FULFILLMENTS                    ("fulfillments"),
    OFFERS                          ("offers"),
    CREDIT_SEARCH                   ("creditsearch"),
    SUBSCRIPTIONS                   ("subscriptions"),
    FINANCES                        ("finances"),
    FINANCIAL_HISTORY               ("financialhistory"),
    CCMP_REQUESTS                   ("ccmprequests"),
    CCMP_RESPONSES                  ("ccmpresponses"),
    SESSIONS                        ("sessions"),
    SCORE_PROCESSOR                 ("scoreprocessor"),
    PRODUCT_SEARCH                  ("products"),
    PRODUCT_LEAD                    ("leads"),
    PRODUCT_HISTORY                 ("producthistory"),
    BROKERS                         ("brokers"),
    RUNPATH                         ("runpath"),
    REPORT_PROCESSOR                ("reportprocessor"),
    FULFILLMENT_SWEEPER             ("fulfillmentsweeper"),
    COMMUNICATION_HISTORY			("communicationhistory"),
    CUSTOMER_OFFER_HISTORY          ("customerofferhistory"),
    SUBSCRIPTION_HISTORY            ("subscriptionhistory"),
    LEGALACCEPTANCES                ("legalacceptances"),
    BASICAUTH                       ("basicAuth"),
    BRANDS                          ("brands"),
    REPORTS                         ("reports"),
    REPORT_SERVICE                  ("reportservice"),
    SCORE_FACTORS                   ("scorefactors"),
    SALESFORCEPUBLISHERS            ("salesforcepublishers"),
    DASREQUEST                      ("dasrequests"),
    DASRESPONSES                    ("dasresponses"),
    ALERT_ENROLLMENTS               ("alertenrollments"),
    CREDIT_ALERT_ENROLLMENTS        ("creditalertenrollments"),
    BILLINGRATEPLANS                ("billingrateplans"),
    BILLINGPAYMENTAUTHORIZATIONS    ("billingpaymentauthorizations"),
    BILLINGSUBSCRIPTIONS            ("billingsubscriptions"),
    BILLINGSUBSCRIPTIONSHISTORY     ("billingsubscriptionhistory"),
    BILLINGPAYMENTMETHODS           ("billingpaymentmethods"),
    BILLINGPROVIDERPROXY            ("billingproviderproxy"),
    BILLINGPAYMENTTRANSACTIONS      ("billingpaymenttransactions"),
    BILLINGVOUCHERS                 ("billingvouchers"),
    ALERTS                          ("alerts"),
    IMPERSONATION                   ("impersonation"),
    FULFILLMENT_DEFER               ("fulfillmentdefers"),
    SUBSCRIPTION_RECON              ("subscriptionreconciler"),
    GATEWAYSSMARTPAYPAYMENTS        ("gatewaysmartpaypayments"),
    BILLINGCUSTOMERPROFILE          ("billingcustomerprofile"),
    BILLINGMIGRATIONS               ("billingmigrations"),
    OFFER_MAESTRO                   ("offermaestro"),
    OAUTH                           ("oauth"),
    DCMSCORES                       ("dcmscores"),
    CASE_HISTORY                    ("casehistory"),
    IMPROVEMENT                     ("improvement"),
    IMPROVEMENT_STORAGE             ("improvementstorage"),
    PRODUCT_CHECK                   ("productcheck"),
    SCORE_IMPROVEMENT_CONTENT       ("scoreimprovementcontent"),
    PARTNER_CUSTOMER                ("partnercustomer"),
    PARTNER_REGISTRATION            ("partnerregistration"),
    PARTNER_TESTHARNESS             ("partnertestharness"),
    BULK_CANCELLER                  ("bulkcanceller"),
    CCMPREQUESTS_HISTORY            ("ccmprequestshistory"),
    CREDIT_SUMMARY                  ("creditsummary"),
    CONSUMER_AUTH					("consumerauth"),
    CREDIT_PROFILE_ORCHESTRATION    ("creditprofileorchestration"),
    ALERTS_BROKER                   ("alertsbroker"),
    PROFILE_MGMT_ORCHESTRATION      ("profilemanagementorchestration"),
    SUBSCRIPTIONAMENDER             ("subscriptionamender"),
    TENANT                          ("tenant"),
    WMCUSTOMER                      ("wmcustomer"),
    WMDATA                          ("wmdata"),
    WMMATCH                         ("wmmatch"),
    PERSONALLOANS                   ("personalloans"),
    SUBSCRIPTIONCHECKER             ("subscriptionchecker");

    String logicalName;

    ServiceName(String logicalName) {
        this.logicalName = logicalName;
    }

    public String getLogicalName() {
        return logicalName;
    }
}

