@boe

Feature: Validate that Edge Cases

  @AUT-3980
  Scenario: C_TC_Verify respone for 400 error
    Given I create a new internal experian boe service request to the /boe/rank endpoint
    And I add the following headers to the request without default parameters
      | x-customer-id | d11e5f3b-a0f5-41b8-9e7b-2c7b1c95de5e |
      | Content-Type  | application/json;charset=UTF-8       |
    And I add a json request body using the file /json_objects/boe/ec_4xx.json
    And I send the POST request with response type ByteArray
    Then The response status code should be 400
    And make sure following attributes exist within response data with correct values
      | Atributes | Value                                              |
      | message   | BOE processing reports missing data in the request |

  @AUT-3981
  Scenario: C_TC_Verify boe response for incorrect input
    Given I create a new internal experian boe service request to the /boe/rank endpoint
    And I add the following headers to the request without default parameters
      | x-customer-id | fee534c6-25d0-4fd1-862e-33ac8a789925 |
      | Content-Type  | application/json;charset=UTF-8       |
    And I add a json request body using the file /json_objects/boe/ec_incorrect_input.json
    And I send the POST request with response type ByteArray
    Then The response status code should be 400
    And make sure following attributes exist within response data with correct values
      | Atributes | Value                                              |
      | message   | BOE processing reports missing data in the request |

  @AUT-3982
  Scenario: C_TC_Verify boe response for missing right_offer_meta_data property
    Given I create a new internal experian boe service request to the /boe/rank endpoint
    And I add the following headers to the request without default parameters
      | x-customer-id | fee534c6-25d0-4fd1-862e-33ac8a789925 |
      | Content-Type  | application/json;charset=UTF-8       |
    And I add a json request body using the file /json_objects/boe/ec_missing_rightoffer.json
    And I send the POST request with response type ByteArray
    Then The response status code should be 400
    And make sure following attributes exist within response data with correct values
      | Atributes | Value                                                           |
      | message   | Validation failed for object='rankingRequestTO'. Error count: 1 |
      | error     | Bad Request                                                     |
      | status    | 400                                                             |

  @AUT-3983
  Scenario: C_TC_Verify boe response for missing loginstat and ConStat
    Given I create a new internal experian boe service request to the /boe/rank endpoint
    And I add the following headers to the request without default parameters
      | x-customer-id | fee534c6-25d0-4fd1-862e-33ac8a789925 |
      | Content-Type  | application/json;charset=UTF-8       |
    And I add a json request body using the file /json_objects/boe/ec_missing_login_con.json
    And I send the POST request with response type ByteArray
    Then The response status code should be 400
    And make sure following attributes exist within response data with correct values
      | Atributes | Value                                                           |
      | message   | Validation failed for object='rankingRequestTO'. Error count: 1 |
      | error     | Bad Request                                                     |
      | status    | 400                                                             |

  @AUT-3984
  Scenario: C_TC_Verify boe response for missing custom_attributes property
    Given I create a new internal experian boe service request to the /boe/rank endpoint
    And I add the following headers to the request without default parameters
      | x-customer-id | fee534c6-25d0-4fd1-862e-33ac8a789925 |
      | Content-Type  | application/json;charset=UTF-8       |
    And I add a json request body using the file /json_objects/boe/ec_missing_custom_attribute.json
    And I send the POST request with response type ByteArray
    Then The response status code should be 200

  @AUT-3985
  Scenario: C_TC_Verify boe response for empty request
    Given I create a new internal experian boe service request to the /boe/rank endpoint
    And I add the following headers to the request without default parameters
      | x-customer-id | fee534c6-25d0-4fd1-862e-33ac8a789925 |
      | Content-Type  | application/json;charset=UTF-8       |
    And I add a json request body using the file /json_objects/boe/empty.json
    And I send the POST request with response type ByteArray
    Then The response status code should be 400
    And make sure following attributes exist within response data with correct values
      | Atributes | Value       |
      | error     | Bad Request |
      | status    | 400         |

  @AUT-3986
  Scenario: C_TC_Verify boe response for wallet default values
    Given I create a new internal experian boe service request to the /boe/rank endpoint
    And I add the following headers to the request without default parameters
      | x-customer-id | fee534c6-25d0-4fd1-862e-33ac8a789925 |
      | Content-Type  | application/json;charset=UTF-8       |
    And I add a json request body using the file /json_objects/boe/ec_wallet_default.json
    And I send the POST request with response type ByteArray
    Then The response status code should be 200

  @AUT-3987
  Scenario: C_TC_Verify boe response for wallet attributes null values
    Given I create a new internal experian boe service request to the /boe/rank endpoint
    And I add the following headers to the request without default parameters
      | x-customer-id | fee534c6-25d0-4fd1-862e-33ac8a789925 |
      | Content-Type  | application/json;charset=UTF-8       |
    And I add a json request body using the file /json_objects/boe/ec_wallet_attribute_null.json
    And I send the POST request with response type ByteArray
    Then The response status code should be 200

  @AUT-3988
  Scenario: C_TC_Verify boe response for wallet empty property
    Given I create a new internal experian boe service request to the /boe/rank endpoint
    And I add the following headers to the request without default parameters
      | x-customer-id | fee534c6-25d0-4fd1-862e-33ac8a789925 |
      | Content-Type  | application/json;charset=UTF-8       |
    And I add a json request body using the file /json_objects/boe/ec_wallet_empty.json
    And I send the POST request with response type ByteArray
    Then The response status code should be 200

  @AUT-3989
  Scenario: C_TC_Verify boe response for reward stock properties empty
    Given I create a new internal experian boe service request to the /boe/rank endpoint
    And I add the following headers to the request without default parameters
      | x-customer-id | fee534c6-25d0-4fd1-862e-33ac8a789925 |
      | Content-Type  | application/json;charset=UTF-8       |
    And I add a json request body using the file /json_objects/boe/ec_rewardstock_empty.json
    And I send the POST request with response type ByteArray
    Then The response status code should be 200

  @AUT-3990
  Scenario: C_TC_Verify boe response for empty vendor offers
    Given I create a new internal experian boe service request to the /boe/rank endpoint
    And I add the following headers to the request without default parameters
      | x-customer-id | fee534c6-25d0-4fd1-862e-33ac8a789925 |
      | Content-Type  | application/json;charset=UTF-8       |
    And I add a json request body using the file /json_objects/boe/ec_empty_vendor.json
    And I send the POST request with response type ByteArray
    Then The response status code should be 400
    And make sure following attributes exist within response data with correct values
      | Atributes | Value                                              |
      | message   | BOE processing reports missing data in the request |

  @AUT-3991
  Scenario: C_TC_Verify boe response for reward stock attributes null
    Given I create a new internal experian boe service request to the /boe/rank endpoint
    And I add the following headers to the request without default parameters
      | x-customer-id | fee534c6-25d0-4fd1-862e-33ac8a789925 |
      | Content-Type  | application/json;charset=UTF-8       |
    And I add a json request body using the file /json_objects/boe/ec_rewardstock_attribute_null.json
    And I send the POST request with response type ByteArray
    Then The response status code should be 200

  @AUT-3992
  Scenario: C_TC_Verify boe response for customs null
    Given I create a new internal experian boe service request to the /boe/rank endpoint
    And I add the following headers to the request without default parameters
      | x-customer-id | fee534c6-25d0-4fd1-862e-33ac8a789925 |
      | Content-Type  | application/json;charset=UTF-8       |
    And I add a json request body using the file /json_objects/boe/ec_customer_null.json
    And I send the POST request with response type ByteArray
    Then The response status code should be 200

  @AUT-3993
  Scenario: C_TC_Verify boe response for no rank source
    Given I create a new internal experian boe service request to the /boe/rank endpoint
    And I add the following headers to the request without default parameters
      | x-customer-id | fee534c6-25d0-4fd1-862e-33ac8a789925 |
      | Content-Type  | application/json;charset=UTF-8       |
    And I add a json request body using the file /json_objects/boe/ec_no_rankscore.json
    And I send the POST request with response type ByteArray
    Then The response status code should be 200
    And make sure following attributes exist within response data with correct values
      | Atributes                        | Value                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
      | fico08                           |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
      | assetInsight                     |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
      | addressMisMatch                  |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
      | derogFlag                        |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
      | mlaFlag                          |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
      | transactionID                    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
      | xfc01                            |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
      | xfc02                            |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
      | xfc03                            |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
      | xfc04                            |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
      | xfc05                            |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
      | xfc05                            |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
      | xfc07                            |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
      | attributes[0].attributes         | contain-debtToIncome itmmPL itmmRET itmmMTG itmmSL incomeInsight itmmHE smCM03 balTransferIndex itmmAU itmmBC                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
      | attributes[0].type               |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
      | attributes[0].bureau             |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
      | attributes[1].attributes         | contain-REH7120 ALL0436 IQB9415 minPLMatPay AUL0416 IQB9417 IQB9410 BCC1360 REV0300 REV5830 BCA0416 BCC0300 ALL8321 ALL7350 BCC5830 AUL0300 BCC5030 BRC5238 PIL8120 ALL5830 REV7112 ALL0300 REV7110 IQT9412 IQT9415 ALL8158 COL3238 IQT9417 MTA8120 REV3422 ALL8151 ALM2001 ILN7110 BCA0300 BCC5421 ALL8270 BCC0416 BCC5427 MTA0400 STU0837 ALM5072 BCC5020 ALL0133 IQF9415 IQF9410 REV5020 BCC0400 ALL9110 COL2750 BCX5830 COL2758 HLC5020 BCA5020 ALL9219 AUL5820 HLC0402 REV5420 ALL5020 AUL5020 BCC5520 STU0336 AUA0300 AUT5020 REH5020 PIL5320 BUS0416 minAUAMatPay MTS0416 REV7420 STU8142 BCX7110 HLC0436 ALL8122 PIL0438 ALL6220 ILN5820 STU0300 MTA0316 ALL7937 REV8120 AUT8120 REV7430 BCC5627 BCC2356 HLC0300 minPLMatTerm minAUAMatTerm BCC5620 PIL5020 ALL0337 BCA8320 BRC3425 STU5092 ALL2870 ALL2116 MTA5020 ALX8220 AUT0300 ALL7370 USE0300 STU0802 BCC7110 MTA0416 ALL0206 STU0807 MTS5020 ALL2106 AUA6280 STU5020 MTS0300 REV2356 REV7801 STU5820 AUT5820 MTA0300 STU0416 STU0812 AUT0416 PIL0300 |
      | attributes[1].type               |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
      | attributes[1].bureau             |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
      | attributes[2].attributes         | contain-SEGMENT_ID TBCA2619 TBCA3619 TBCA2615 TBCA2616 TAPS4_SUMAVE_BAL TBCA3527 TBCA3601 TV_REV_AVG_BAL_6_MON TAPS4_SPEND TAPS4_TRD_CNT_SPEND TBCA2106 TBCA2601 TAUA3702 TRTR2613 TBCA3105 TBCA3301 TV_REV_AVG_BAL_12_MON TBCA2265 TBCA2271                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
      | attributes[2].type               |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
      | attributes[2].bureau             |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
      | attributes[3].attributes         | contain-GROUP REV_recFeature                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
      | attributes[3].type               |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
      | attributes[3].bureau             |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
      | offers[0].type                   | notnull                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |
      | offers[1].type                   | notnull                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |
      | offers[2].type                   | notnull                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |
      | offers[3].type                   | notnull                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |
      | credit_style1.trades[0].count    | notnull                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |
      | credit_style1.trades[0].accounts | contain-terms amount1 amount1qualifier amount2 amount2qualifier balanceDate balanceAmount openClosed revInstall monthlyPaymentAmount monthlyPaymentType subscriberName accountConditionCode enhancedStatusCode enhancedTypeCode dateOpen                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |

  @AUT-3994
  Scenario: C_TC_Verify boe response for incorrect term value
    Given I create a new internal experian boe service request to the /boe/rank endpoint
    And I add the following headers to the request without default parameters
      | x-customer-id | fee534c6-25d0-4fd1-862e-33ac8a789925 |
      | Content-Type  | application/json;charset=UTF-8       |
    And I add a json request body using the file /json_objects/boe/ec_incorrect_terms.json
    And I send the POST request with response type ByteArray
    Then The response status code should be 400
    And make sure following attributes exist within response data with correct values
      | Atributes | Value                                              |
      | message   | BOE processing reports missing data in the request |




